Repository SWM-BetterLife/AntiFragile-Backend, pull requests merged in 2024-07, with the labels that each got.

#8 Feat: 스프링 시큐리티, JWT, OAuth2 구글
  .gitignore
  build.gradle
  docker-compose.yml
  redis/data/dump.rdb
  src/main/java/swm/betterlife/antifragile/common/config/AppConfig.java
  src/main/java/swm/betterlife/antifragile/common/config/RedisConfig.java
  src/main/java/swm/betterlife/antifragile/common/config/SecurityConfig.java
  src/main/java/swm/betterlife/antifragile/common/exception/BaseException.java
  src/main/java/swm/betterlife/antifragile/common/exception/LoginRequiredException.java
  src/main/java/swm/betterlife/antifragile/common/exception/RefreshTokenNotValidatedException.java
  src/main/java/swm/betterlife/antifragile/common/exception/TokenExpiredException.java
  src/main/java/swm/betterlife/antifragile/common/exception/code/ErrorCode.java
  src/main/java/swm/betterlife/antifragile/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/swm/betterlife/antifragile/common/jwt/constant/JwtConstant.java
  src/main/java/swm/betterlife/antifragile/common/jwt/filter/JwtAuthFilter.java
  src/main/java/swm/betterlife/antifragile/common/jwt/filter/JwtAuthenticationEntryPoint.java
  src/main/java/swm/betterlife/antifragile/common/jwt/filter/JwtExceptionFilter.java
  src/main/java/swm/betterlife/antifragile/common/jwt/util/JwtProvider.java
  src/main/java/swm/betterlife/antifragile/common/oauth/Oauth2Attribute.java
  src/main/java/swm/betterlife/antifragile/common/oauth/Oauth2LoginSuccessHandler.java
  src/main/java/swm/betterlife/antifragile/common/oauth/Oauth2UserService.java
  src/main/java/swm/betterlife/antifragile/common/response/ResponseBody.java
  src/main/java/swm/betterlife/antifragile/common/response/Status.java
  src/main/java/swm/betterlife/antifragile/common/security/PrincipalDetails.java
  src/main/java/swm/betterlife/antifragile/common/security/PrincipalDetailsService.java
  src/main/java/swm/betterlife/antifragile/domain/auth/controller/AuthController.java
  src/main/java/swm/betterlife/antifragile/domain/auth/dto/LoginRequest.java
  src/main/java/swm/betterlife/antifragile/domain/auth/dto/LoginResponse.java
  src/main/java/swm/betterlife/antifragile/domain/auth/dto/SignUpRequest.java
  src/main/java/swm/betterlife/antifragile/domain/auth/dto/SignUpResponse.java
  src/main/java/swm/betterlife/antifragile/domain/auth/service/AuthService.java
  src/main/java/swm/betterlife/antifragile/domain/member/controller/MemberController.java
  src/main/java/swm/betterlife/antifragile/domain/member/dto/MemberDetailResponse.java
  src/main/java/swm/betterlife/antifragile/domain/member/entity/Member.java
  src/main/java/swm/betterlife/antifragile/domain/member/entity/RoleType.java
  src/main/java/swm/betterlife/antifragile/domain/member/repository/MemberRepository.java
  src/main/java/swm/betterlife/antifragile/domain/member/service/MemberService.java
  src/main/java/swm/betterlife/antifragile/domain/token/controller/TokenController.java
  src/main/java/swm/betterlife/antifragile/domain/token/dto/TokenIssueResponse.java
  src/main/java/swm/betterlife/antifragile/domain/token/dto/TokenReIssueRequest.java
  src/main/java/swm/betterlife/antifragile/domain/token/entity/Token.java
  src/main/java/swm/betterlife/antifragile/domain/token/repository/TokenRepository.java
  src/main/java/swm/betterlife/antifragile/domain/token/service/TokenService.java
  src/main/resources/application.properties
Labels: feature

#10 feat: Member API 구현
  .gitignore
  gradlew
  redis/data/dump.rdb
  src/main/java/swm/betterlife/antifragile/common/config/MongoConfig.java
  src/main/java/swm/betterlife/antifragile/common/exception/MemberNotFoundException.java
  src/main/java/swm/betterlife/antifragile/common/exception/code/ErrorCode.java
  src/main/java/swm/betterlife/antifragile/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/swm/betterlife/antifragile/common/jwt/constant/JwtConstant.java
  src/main/java/swm/betterlife/antifragile/common/response/ResponseBody.java
  src/main/java/swm/betterlife/antifragile/domain/auth/controller/AuthController.java
  src/main/java/swm/betterlife/antifragile/domain/member/controller/MemberController.java
  src/main/java/swm/betterlife/antifragile/domain/member/dto/MemberDetailResponse.java
  src/main/java/swm/betterlife/antifragile/domain/member/dto/NicknameModifyRequest.java
  src/main/java/swm/betterlife/antifragile/domain/member/dto/ProfileImgModifyRequest.java
  src/main/java/swm/betterlife/antifragile/domain/member/entity/Member.java
  src/main/java/swm/betterlife/antifragile/domain/member/repository/MemberRepository.java
  src/main/java/swm/betterlife/antifragile/domain/member/service/MemberService.java
  src/test/java/swm/betterlife/antifragile/AntiFragileApplicationTests.java
Labels: feature

#12 feat: 로그아웃 API 구현
  src/main/java/swm/betterlife/antifragile/domain/auth/controller/AuthController.java
  src/main/java/swm/betterlife/antifragile/domain/auth/dto/LogoutRequest.java
  src/main/java/swm/betterlife/antifragile/domain/auth/service/AuthService.java
  src/main/java/swm/betterlife/antifragile/domain/token/service/TokenService.java
Labels: feature

#18 feat: S3Config Class 작성
  build.gradle
  src/main/java/swm/betterlife/antifragile/common/config/S3Config.java
Labels: feature

#19 refactor: PrincipalDetails에 memberId 필드 추가
  src/main/java/swm/betterlife/antifragile/common/jwt/constant/JwtConstant.java
  src/main/java/swm/betterlife/antifragile/common/jwt/filter/JwtAuthFilter.java
  src/main/java/swm/betterlife/antifragile/common/jwt/filter/JwtAuthenticationEntryPoint.java
  src/main/java/swm/betterlife/antifragile/common/jwt/util/JwtProvider.java
  src/main/java/swm/betterlife/antifragile/common/security/PrincipalDetails.java
  src/main/java/swm/betterlife/antifragile/common/security/PrincipalDetailsService.java
  src/main/java/swm/betterlife/antifragile/domain/auth/service/AuthService.java
  src/main/java/swm/betterlife/antifragile/domain/token/controller/TokenController.java
  src/main/java/swm/betterlife/antifragile/domain/token/entity/Token.java
  src/main/java/swm/betterlife/antifragile/domain/token/service/TokenService.java
Labels: refactoring

#20 feat: cd 구축을 위한 cd.yml과 Dockerfile 추가
  .github/workflows/cd.yml
  Dockerfile
Labels: feature

#25 SWM-92 refactor: Entity Id 타입 String으로 변경
  src/main/java/swm/betterlife/antifragile/common/jwt/util/JwtProvider.java
  src/main/java/swm/betterlife/antifragile/common/oauth/Oauth2LoginSuccessHandler.java
  src/main/java/swm/betterlife/antifragile/common/security/PrincipalDetails.java
  src/main/java/swm/betterlife/antifragile/domain/auth/controller/AuthController.java
  src/main/java/swm/betterlife/antifragile/domain/auth/dto/request/LoginRequest.java
  src/main/java/swm/betterlife/antifragile/domain/auth/dto/request/LogoutRequest.java
  src/main/java/swm/betterlife/antifragile/domain/auth/dto/request/SignUpRequest.java
  src/main/java/swm/betterlife/antifragile/domain/auth/dto/response/LoginResponse.java
  src/main/java/swm/betterlife/antifragile/domain/auth/dto/response/SignUpResponse.java
  src/main/java/swm/betterlife/antifragile/domain/auth/service/AuthService.java
  src/main/java/swm/betterlife/antifragile/domain/content/entity/Content.java
  src/main/java/swm/betterlife/antifragile/domain/content/entity/SaveMember.java
  src/main/java/swm/betterlife/antifragile/domain/contentreview/entity/ContentReview.java
  src/main/java/swm/betterlife/antifragile/domain/contentreview/entity/ReviewMember.java
  src/main/java/swm/betterlife/antifragile/domain/diaryanalysis/entity/DiaryAnalysis.java
  src/main/java/swm/betterlife/antifragile/domain/diaryanalysis/entity/RecommendContent.java
  src/main/java/swm/betterlife/antifragile/domain/diaryanalysis/entity/SelectedEmoticon.java
  src/main/java/swm/betterlife/antifragile/domain/emoticontheme/entity/EmoticonTheme.java
  src/main/java/swm/betterlife/antifragile/domain/member/controller/MemberController.java
  src/main/java/swm/betterlife/antifragile/domain/member/dto/request/NicknameModifyRequest.java
  src/main/java/swm/betterlife/antifragile/domain/member/dto/request/ProfileImgModifyRequest.java
  src/main/java/swm/betterlife/antifragile/domain/member/dto/response/MemberDetailResponse.java
  src/main/java/swm/betterlife/antifragile/domain/member/entity/Member.java
  src/main/java/swm/betterlife/antifragile/domain/member/service/MemberService.java
  src/main/java/swm/betterlife/antifragile/domain/pointreceipt/entity/PointReceipt.java
  src/main/java/swm/betterlife/antifragile/domain/recentcontent/entity/ContentRecord.java
  src/main/java/swm/betterlife/antifragile/domain/recentcontent/entity/RecentContent.java
  src/main/java/swm/betterlife/antifragile/domain/token/controller/TokenController.java
  src/main/java/swm/betterlife/antifragile/domain/token/dto/request/TokenReIssueRequest.java
  src/main/java/swm/betterlife/antifragile/domain/token/dto/response/TokenIssueResponse.java
  src/main/java/swm/betterlife/antifragile/domain/token/repository/TokenRepository.java
  src/main/java/swm/betterlife/antifragile/domain/token/service/TokenService.java
Labels: refactoring

#22 SWM-19 feat: 이모티콘 테마 API 구현
  src/main/java/swm/betterlife/antifragile/AntiFragileApplication.java
  src/main/java/swm/betterlife/antifragile/common/config/SecurityConfig.java
  src/main/java/swm/betterlife/antifragile/common/exception/EmoticonThemeAlreadyHasMemberId.java
  src/main/java/swm/betterlife/antifragile/common/exception/EmoticonThemeNotFoundException.java
  src/main/java/swm/betterlife/antifragile/common/exception/IllegalObjectIdException.java
  src/main/java/swm/betterlife/antifragile/common/exception/code/ErrorCode.java
  src/main/java/swm/betterlife/antifragile/common/jwt/filter/JwtAuthFilter.java
  src/main/java/swm/betterlife/antifragile/common/jwt/util/JwtProvider.java
  src/main/java/swm/betterlife/antifragile/common/response/PagingResponse.java
  src/main/java/swm/betterlife/antifragile/common/security/PrincipalDetails.java
  src/main/java/swm/betterlife/antifragile/common/util/CollectionName.java
  src/main/java/swm/betterlife/antifragile/common/util/ObjectIdGenerator.java
  src/main/java/swm/betterlife/antifragile/domain/content/entity/Content.java
  src/main/java/swm/betterlife/antifragile/domain/emoticontheme/controller/EmoticonThemeController.java
  src/main/java/swm/betterlife/antifragile/domain/emoticontheme/dto/response/EmoticonEntireResponse.java
  src/main/java/swm/betterlife/antifragile/domain/emoticontheme/dto/response/EmoticonInfoResponse.java
  src/main/java/swm/betterlife/antifragile/domain/emoticontheme/dto/response/EmoticonThemeOwnDetailResponse.java
  src/main/java/swm/betterlife/antifragile/domain/emoticontheme/dto/response/EmoticonThemeOwnEntireResponse.java
  src/main/java/swm/betterlife/antifragile/domain/emoticontheme/dto/response/EmoticonThemeSummaryResponse.java
  src/main/java/swm/betterlife/antifragile/domain/emoticontheme/repository/EmoticonThemeRepository.java
  src/main/java/swm/betterlife/antifragile/domain/emoticontheme/service/EmoticonThemeService.java
  src/main/java/swm/betterlife/antifragile/domain/member/repository/MemberRepository.java
  src/main/java/swm/betterlife/antifragile/domain/recentcontent/entity/RecentContent.java
Labels: feature

#29 feat: DiaryAnalysis 관련 API 구현
  src/main/java/swm/betterlife/antifragile/common/exception/DiaryAnalysisAlreadyExistedException.java
  src/main/java/swm/betterlife/antifragile/common/exception/DiaryAnalysisNotFoundException.java
  src/main/java/swm/betterlife/antifragile/common/exception/code/ErrorCode.java
  src/main/java/swm/betterlife/antifragile/domain/diaryanalysis/controller/DiaryAnalysisController.java
  src/main/java/swm/betterlife/antifragile/domain/diaryanalysis/dto/request/ModifyDiaryAnalysisRequest.java
  src/main/java/swm/betterlife/antifragile/domain/diaryanalysis/dto/request/SaveDiaryAnalysisRequest.java
  src/main/java/swm/betterlife/antifragile/domain/diaryanalysis/entity/DiaryAnalysis.java
  src/main/java/swm/betterlife/antifragile/domain/diaryanalysis/repository/DiaryAnalysisRepository.java
  src/main/java/swm/betterlife/antifragile/domain/diaryanalysis/service/DiaryAnalysisService.java
Labels: feature

#30 feat: 포인트 API 구현
  src/main/java/swm/betterlife/antifragile/common/config/MongoConfig.java
  src/main/java/swm/betterlife/antifragile/common/exception/MemberPointNotFoundException.java
  src/main/java/swm/betterlife/antifragile/common/exception/code/ErrorCode.java
  src/main/java/swm/betterlife/antifragile/common/oauth/Oauth2LoginSuccessHandler.java
  src/main/java/swm/betterlife/antifragile/domain/auth/controller/AuthController.java
  src/main/java/swm/betterlife/antifragile/domain/auth/dto/request/AuthLoginRequest.java
  src/main/java/swm/betterlife/antifragile/domain/auth/dto/request/AuthLogoutRequest.java
  src/main/java/swm/betterlife/antifragile/domain/auth/dto/request/AuthSignUpRequest.java
  src/main/java/swm/betterlife/antifragile/domain/auth/dto/response/AuthLoginResponse.java
  src/main/java/swm/betterlife/antifragile/domain/auth/dto/response/AuthSignUpResponse.java
  src/main/java/swm/betterlife/antifragile/domain/auth/dto/response/LoginResponse.java
  src/main/java/swm/betterlife/antifragile/domain/auth/dto/response/SignUpResponse.java
  src/main/java/swm/betterlife/antifragile/domain/auth/service/AuthService.java
  src/main/java/swm/betterlife/antifragile/domain/member/controller/MemberController.java
  src/main/java/swm/betterlife/antifragile/domain/member/dto/response/MemberDetailResponse.java
  src/main/java/swm/betterlife/antifragile/domain/member/entity/Member.java
  src/main/java/swm/betterlife/antifragile/domain/member/entity/MemberPoint.java
  src/main/java/swm/betterlife/antifragile/domain/member/repository/MemberPointRepository.java
  src/main/java/swm/betterlife/antifragile/domain/member/repository/MemberRepository.java
  src/main/java/swm/betterlife/antifragile/domain/member/service/MemberPointService.java
  src/main/java/swm/betterlife/antifragile/domain/member/service/MemberService.java
  src/main/java/swm/betterlife/antifragile/domain/pointreceipt/controller/PointReceiptController.java
  src/main/java/swm/betterlife/antifragile/domain/pointreceipt/dto/request/PointChargeRequest.java
  src/main/java/swm/betterlife/antifragile/domain/pointreceipt/dto/response/PointChargeResponse.java
  src/main/java/swm/betterlife/antifragile/domain/pointreceipt/dto/response/PointReceiptDetailResponse.java
  src/main/java/swm/betterlife/antifragile/domain/pointreceipt/dto/response/PurchaseItemResponse.java
  src/main/java/swm/betterlife/antifragile/domain/pointreceipt/entity/Item.java
  src/main/java/swm/betterlife/antifragile/domain/pointreceipt/entity/ItemType.java
  src/main/java/swm/betterlife/antifragile/domain/pointreceipt/entity/PointReceipt.java
  src/main/java/swm/betterlife/antifragile/domain/pointreceipt/repository/PointReceiptRepository.java
  src/main/java/swm/betterlife/antifragile/domain/pointreceipt/service/PointReceiptService.java
Labels: feature

#31 feat: content get api
  src/main/java/swm/betterlife/antifragile/common/exception/ContentAlreadyLikedException.java
  src/main/java/swm/betterlife/antifragile/common/exception/ContentNotLikedException.java
  src/main/java/swm/betterlife/antifragile/common/exception/RecommendedContentNotFoundException.java
  src/main/java/swm/betterlife/antifragile/common/exception/code/ErrorCode.java
  src/main/java/swm/betterlife/antifragile/domain/content/controller/ContentController.java
  src/main/java/swm/betterlife/antifragile/domain/content/dto/response/ContentDetailResponse.java
  src/main/java/swm/betterlife/antifragile/domain/content/dto/response/ContentRecommendResponse.java
  src/main/java/swm/betterlife/antifragile/domain/content/entity/Content.java
  src/main/java/swm/betterlife/antifragile/domain/content/entity/YouTubeInfo.java
  src/main/java/swm/betterlife/antifragile/domain/content/repository/ContentRepository.java
  src/main/java/swm/betterlife/antifragile/domain/content/service/ContentService.java
  src/main/java/swm/betterlife/antifragile/domain/content/service/MockDataProvider.java
  src/main/java/swm/betterlife/antifragile/domain/diaryanalysis/entity/RecommendContent.java
  src/main/java/swm/betterlife/antifragile/domain/member/controller/MemberController.java
  src/main/java/swm/betterlife/antifragile/domain/member/dto/response/MemberRemainNumberResponse.java
  src/main/java/swm/betterlife/antifragile/domain/member/service/MemberService.java
Labels: feature, fix

#34 feat: 프로필 이미지 수정 시 S3 업데이트 적용
  src/main/java/swm/betterlife/antifragile/common/util/S3ImageCategory.java
  src/main/java/swm/betterlife/antifragile/common/util/S3ImageComponent.java
  src/main/java/swm/betterlife/antifragile/domain/content/service/ContentService.java
  src/main/java/swm/betterlife/antifragile/domain/member/controller/MemberController.java
  src/main/java/swm/betterlife/antifragile/domain/member/dto/request/ProfileImgModifyRequest.java
  src/main/java/swm/betterlife/antifragile/domain/member/service/MemberService.java
Labels: refactoring

#36 feat: modify dev cd
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  docker-compose.dev.yml
Labels: feature

#40 feat: Content DB 설계 변경 및 API 로직 수정
  src/main/java/swm/betterlife/antifragile/common/exception/DatabaseUpdateFailException.java
  src/main/java/swm/betterlife/antifragile/common/exception/DatabaseUpsertFailException.java
  src/main/java/swm/betterlife/antifragile/common/exception/code/ErrorCode.java
  src/main/java/swm/betterlife/antifragile/domain/content/controller/ContentController.java
  src/main/java/swm/betterlife/antifragile/domain/content/dto/response/ContentRecommendResponse.java
  src/main/java/swm/betterlife/antifragile/domain/content/entity/Content.java
  src/main/java/swm/betterlife/antifragile/domain/content/repository/ContentRepository.java
  src/main/java/swm/betterlife/antifragile/domain/content/service/ContentQueryService.java
  src/main/java/swm/betterlife/antifragile/domain/content/service/ContentService.java
  src/main/java/swm/betterlife/antifragile/domain/diaryanalysis/entity/DiaryAnalysis.java
  src/main/java/swm/betterlife/antifragile/domain/diaryanalysis/entity/RecommendContent.java
  src/main/java/swm/betterlife/antifragile/domain/diaryanalysis/service/DiaryAnalysisService.java
  src/main/java/swm/betterlife/antifragile/domain/recentcontent/controller/RecentContentController.java
  src/main/java/swm/betterlife/antifragile/domain/recentcontent/entity/ContentRecord.java
  src/main/java/swm/betterlife/antifragile/domain/recentcontent/repository/RecentContentRepository.java
  src/main/java/swm/betterlife/antifragile/domain/recentcontent/service/RecentContentService.java
Labels: feature, fix, refactoring

#41 feat: OpenAI api
  src/main/java/swm/betterlife/antifragile/common/config/OpenAiConfig.java
  src/main/java/swm/betterlife/antifragile/domain/recommend/controller/RecommendController.java
  src/main/java/swm/betterlife/antifragile/domain/recommend/dto/OpenAiMessage.java
  src/main/java/swm/betterlife/antifragile/domain/recommend/dto/request/OpenAiRequest.java
  src/main/java/swm/betterlife/antifragile/domain/recommend/dto/response/OpenAiResponse.java
  src/main/java/swm/betterlife/antifragile/domain/recommend/service/RecommendService.java
Labels: feature

#42 feat: MongoConfig 트랜잭션 매니저 추가
  src/main/java/swm/betterlife/antifragile/common/config/MongoConfig.java
Labels: feature

#49 fix: Auth, Member 코드 오류 수정
  src/main/java/swm/betterlife/antifragile/common/config/SecurityConfig.java
  src/main/java/swm/betterlife/antifragile/domain/auth/controller/AuthController.java
  src/main/java/swm/betterlife/antifragile/domain/auth/service/AuthService.java
  src/main/java/swm/betterlife/antifragile/domain/emoticontheme/service/EmoticonThemeService.java
  src/main/java/swm/betterlife/antifragile/domain/member/controller/MemberController.java
  src/main/java/swm/betterlife/antifragile/domain/member/controller/MemberNicknameDuplResponse.java
  src/main/java/swm/betterlife/antifragile/domain/member/dto/request/MemberProfileModifyRequest.java
  src/main/java/swm/betterlife/antifragile/domain/member/dto/response/MemberProfileModifyResponse.java
  src/main/java/swm/betterlife/antifragile/domain/member/entity/Gender.java
  src/main/java/swm/betterlife/antifragile/domain/member/entity/Member.java
  src/main/java/swm/betterlife/antifragile/domain/member/repository/MemberRepository.java
  src/main/java/swm/betterlife/antifragile/domain/member/service/MemberService.java
  src/main/java/swm/betterlife/antifragile/domain/token/controller/TokenController.java
Labels: fix

#51 feat: api refactoring
  src/main/java/swm/betterlife/antifragile/domain/diaryanalysis/controller/DiaryAnalysisController.java
  src/main/java/swm/betterlife/antifragile/domain/diaryanalysis/dto/request/DiaryAnalysisModifyRequest.java
  src/main/java/swm/betterlife/antifragile/domain/diaryanalysis/dto/request/DiaryAnalysisSaveRequest.java
  src/main/java/swm/betterlife/antifragile/domain/diaryanalysis/dto/response/EmoticonMonthlyResponse.java
  src/main/java/swm/betterlife/antifragile/domain/diaryanalysis/dto/response/EmotionDailyResponse.java
  src/main/java/swm/betterlife/antifragile/domain/diaryanalysis/entity/SelectedEmoticon.java
  src/main/java/swm/betterlife/antifragile/domain/diaryanalysis/service/DiaryAnalysisService.java
  src/main/java/swm/betterlife/antifragile/domain/emoticontheme/service/EmoticonThemeService.java
  src/main/java/swm/betterlife/antifragile/domain/member/controller/MemberController.java
Labels: refactoring
