Repository SWM-BetterLife/AntiFragile-Backend, pull requests merged in 2024-08, with the labels that each got.

#58 SWM-105 feat: 특정 감정에 대해 테마별 이모티코 전체 조회 api 구현
  src/main/java/swm/betterlife/antifragile/domain/emoticontheme/controller/EmoticonThemeController.java
  src/main/java/swm/betterlife/antifragile/domain/emoticontheme/dto/response/EmoticonEntireFromEmotionResponse.java
  src/main/java/swm/betterlife/antifragile/domain/emoticontheme/dto/response/EmoticonInfoFromEmotionResponse.java
  src/main/java/swm/betterlife/antifragile/domain/emoticontheme/repository/EmoticonThemeRepository.java
  src/main/java/swm/betterlife/antifragile/domain/emoticontheme/service/EmoticonThemeService.java
Labels: feature

#56 feat: YouTube 검색 구현
  build.gradle
  src/main/java/swm/betterlife/antifragile/common/exception/YouTubeApiException.java
  src/main/java/swm/betterlife/antifragile/common/exception/code/ErrorCode.java
  src/main/java/swm/betterlife/antifragile/domain/content/entity/Content.java
  src/main/java/swm/betterlife/antifragile/domain/content/service/ContentService.java
  src/main/java/swm/betterlife/antifragile/domain/content/service/MockDataProvider.java
  src/main/java/swm/betterlife/antifragile/domain/member/entity/Gender.java
  src/main/java/swm/betterlife/antifragile/domain/member/service/MemberService.java
  src/main/java/swm/betterlife/antifragile/domain/recommend/controller/RecommendController.java
  src/main/java/swm/betterlife/antifragile/domain/recommend/dto/request/RecommendPromptRequest.java
  src/main/java/swm/betterlife/antifragile/domain/recommend/dto/response/YouTubeResponse.java
  src/main/java/swm/betterlife/antifragile/domain/recommend/service/RecommendService.java
Labels: feature

#61 refactor: EmotionDailyResponse에 emoticon 추가
  src/main/java/swm/betterlife/antifragile/domain/diaryanalysis/dto/response/EmotionDailyResponse.java
  src/main/java/swm/betterlife/antifragile/domain/diaryanalysis/service/DiaryAnalysisService.java
Labels: feature, refactoring

#64 feat: UTC에 맞춰서 Timezone 조정하는 컨버터 구현
  src/main/java/swm/betterlife/antifragile/common/config/MongoConfig.java
  src/main/java/swm/betterlife/antifragile/common/config/TimeZoneConfig.java
  src/main/java/swm/betterlife/antifragile/common/converter/ReadingLocalDateTimeToKstConverter.java
  src/main/java/swm/betterlife/antifragile/common/converter/ReadingLocalDateToKstConverter.java
  src/main/java/swm/betterlife/antifragile/common/converter/WritingLocalDateTimeToKstConverter.java
  src/main/java/swm/betterlife/antifragile/common/converter/WritingLocalDateToKstConverter.java
Labels: feature

#63 fix: 회원가입 시 memberpoint, memberdiary 조회 시 오류 수정
  src/main/java/swm/betterlife/antifragile/common/exception/MemberPointNotFoundException.java
  src/main/java/swm/betterlife/antifragile/common/exception/code/ErrorCode.java
  src/main/java/swm/betterlife/antifragile/domain/member/entity/MemberPoint.java
  src/main/java/swm/betterlife/antifragile/domain/member/repository/MemberDiaryRepository.java
  src/main/java/swm/betterlife/antifragile/domain/member/repository/MemberPointRepository.java
  src/main/java/swm/betterlife/antifragile/domain/member/service/MemberPointService.java
Labels: bug, fix

#68 refactor: 로그인 시 Request에 비밀번호 추가, 가입 여부 확인 API 구현
  build.gradle
  src/main/java/swm/betterlife/antifragile/common/config/SecurityConfig.java
  src/main/java/swm/betterlife/antifragile/common/oauth/Oauth2Attribute.java
  src/main/java/swm/betterlife/antifragile/common/oauth/Oauth2LoginSuccessHandler.java
  src/main/java/swm/betterlife/antifragile/common/oauth/Oauth2UserService.java
  src/main/java/swm/betterlife/antifragile/domain/auth/controller/AuthController.java
  src/main/java/swm/betterlife/antifragile/domain/auth/dto/request/AuthLoginRequest.java
  src/main/java/swm/betterlife/antifragile/domain/auth/dto/request/AuthSignUpRequest.java
  src/main/java/swm/betterlife/antifragile/domain/auth/service/AuthService.java
  src/main/java/swm/betterlife/antifragile/domain/member/controller/MemberController.java
  src/main/java/swm/betterlife/antifragile/domain/member/dto/response/MemberExistenceResponse.java
  src/main/java/swm/betterlife/antifragile/domain/member/service/MemberService.java
Labels: feature

#66 feat: 콘텐츠 response 수정
  src/main/java/swm/betterlife/antifragile/common/converter/WritingLocalDateToKstConverter.java
  src/main/java/swm/betterlife/antifragile/domain/content/controller/ContentController.java
  src/main/java/swm/betterlife/antifragile/domain/content/dto/response/ChannelResponse.java
  src/main/java/swm/betterlife/antifragile/domain/content/dto/response/ContentDetailResponse.java
  src/main/java/swm/betterlife/antifragile/domain/content/dto/response/ContentListResponse.java
  src/main/java/swm/betterlife/antifragile/domain/content/dto/response/ContentRecommendResponse.java
  src/main/java/swm/betterlife/antifragile/domain/content/entity/YouTubeInfo.java
  src/main/java/swm/betterlife/antifragile/domain/content/service/ContentQueryService.java
  src/main/java/swm/betterlife/antifragile/domain/content/service/ContentService.java
  src/main/java/swm/betterlife/antifragile/domain/emoticontheme/controller/EmoticonThemeController.java
  src/main/java/swm/betterlife/antifragile/domain/emoticontheme/service/EmoticonThemeService.java
  src/main/java/swm/betterlife/antifragile/domain/recommend/dto/response/YouTubeResponse.java
  src/main/java/swm/betterlife/antifragile/domain/recommend/service/RecommendService.java
Labels: feature, refactoring

#69 회원가입 시 프로필 이미지 업로드 및 S3 url 변수 분리 및 회원가입 로직 수정
  src/main/java/swm/betterlife/antifragile/common/util/S3ImageComponent.java
  src/main/java/swm/betterlife/antifragile/domain/auth/controller/AuthController.java
  src/main/java/swm/betterlife/antifragile/domain/auth/dto/request/AuthSignUpRequest.java
  src/main/java/swm/betterlife/antifragile/domain/auth/dto/response/AuthLoginResponse.java
  src/main/java/swm/betterlife/antifragile/domain/auth/dto/response/AuthSignUpResponse.java
  src/main/java/swm/betterlife/antifragile/domain/auth/service/AuthService.java
  src/main/java/swm/betterlife/antifragile/domain/contentreview/entity/ReviewMember.java
  src/main/java/swm/betterlife/antifragile/domain/member/dto/response/MemberDetailResponse.java
  src/main/java/swm/betterlife/antifragile/domain/member/entity/Member.java
  src/main/java/swm/betterlife/antifragile/domain/member/service/MemberService.java
Labels: feature

#70 feat: Age -> birthDate 변경 및 프로필 상세 조회 구현
  src/main/java/swm/betterlife/antifragile/common/util/AgeConverter.java
  src/main/java/swm/betterlife/antifragile/common/util/ObjectIdGenerator.java
  src/main/java/swm/betterlife/antifragile/domain/auth/dto/request/AuthSignUpRequest.java
  src/main/java/swm/betterlife/antifragile/domain/auth/service/AuthService.java
  src/main/java/swm/betterlife/antifragile/domain/emoticontheme/service/EmoticonThemeService.java
  src/main/java/swm/betterlife/antifragile/domain/member/controller/MemberController.java
  src/main/java/swm/betterlife/antifragile/domain/member/dto/request/MemberProfileModifyRequest.java
  src/main/java/swm/betterlife/antifragile/domain/member/dto/response/MemberDetailInfoResponse.java
  src/main/java/swm/betterlife/antifragile/domain/member/dto/response/MemberInfoResponse.java
  src/main/java/swm/betterlife/antifragile/domain/member/dto/response/MemberProfileModifyResponse.java
  src/main/java/swm/betterlife/antifragile/domain/member/entity/Member.java
  src/main/java/swm/betterlife/antifragile/domain/member/service/MemberService.java
  src/main/java/swm/betterlife/antifragile/domain/recommend/service/RecommendService.java
Labels: feature, refactoring

#73 refactor: YouTube API 고화질 thumbnail, 임베딩 가능 영상만 추출
  src/main/java/swm/betterlife/antifragile/domain/recommend/service/RecommendService.java
Labels: feature
